print(1)
GenerateObj("log","OBJ//log.obj","Image//log.tga")
GenerateObj("log2", "OBJ//log.obj","Image//log2.tga")
GenerateObj("log3", "OBJ//log.obj","Image//log3.tga")
GenerateObj("left", "OBJ//leftside.obj", "Image//farmhouse.tga")
GenerateObj("right", "OBJ//rightside.obj", "Image//farmhouse.tga")
GenerateObj("floor", "OBJ//plank.obj", "Image//farmhouse.tga")
GenerateObj("roof", "OBJ//rooftop.obj", "Image//farmhouse.tga")
GenerateObj("entrance", "OBJ//roofentrance.obj", "Image//farmhouse.tga")
GenerateObj("bus", "OBJ//bus.obj", "Image//busuv.tga")
GenerateObj("bus2", "OBJ//bus.obj", "Image//busuv2.tga")
GenerateObj("bus3", "OBJ//bus.obj", "Image//busuv3.tga")
GenerateObj("clocktower", "OBJ//clocktower.obj", "Image//bigben.tga")
GenerateObj("clocktower2", "OBJ//clocktower.obj", "Image//bigben2.tga")
GenerateObj("clocktower3", "OBJ//clocktower.obj", "Image//bigben3.tga")
GenerateObj("tree", "OBJ//tree1.obj", "Image//tree1.tga")
GenerateObj("tree2", "OBJ//tree2.obj", "Image//tree2.tga")
GenerateObj("tree3", "OBJ//tree3.obj", "Image//tree2.tga")
GenerateObj("tree4", "OBJ//tree4.obj", "Image//tree2.tga")
GenerateObj("robot", "OBJ//robotfull.obj", "Image//enemy.tga")
GenerateObj("robot2", "OBJ//robotfull.obj", "Image//enemy2.tga")
GenerateObj("robot3", "OBJ//robotfull.obj", "Image//enemy3.tga")
GenerateObj("robothands", "OBJ//robothands.obj", "Image//enemy.tga")
GenerateObj("tanktop", "OBJ//tanktop.obj", "Image//tank.tga")
GenerateObj("tankbody", "OBJ//tankbody3.obj", "Image//tank.tga")
GenerateObj("tankbody2", "OBJ//tankbody2.obj", "Image//tank.tga")
GenerateObj("tankbody3", "OBJ//tankbody.obj", "Image//tank.tga")